package com.example.lenovo.mobilehub;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.ArrayList;

public class Trial extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_trial);

        FirebaseDatabase database = FirebaseDatabase.getInstance();
        DatabaseReference myRef2 = database.getReference("Items");



        /*Item I1=new Item();
        I1.setName("Deadpool");
        I1.setGenre("Comedy");
        I1.setImageLink("https://m.media-amazon.com/images/M/MV5BYzE5MjY1ZDgtMTkyNC00MTMyLThhMjAtZGI5OTE1NzFlZGJjXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0,0,182,268_AL_.jpg");
        */



       /* Item I3=new Item();
        I3.setId(3);
        I3.setName("The Nun");
        I3.setGenre("Horror");
        I3.setImageLink("https://m.media-amazon.com/images/M/MV5BMjM3NzQ5NDcxOF5BMl5BanBnXkFtZTgwNzM4MTQ5NTM@._V1_UX182_CR0,0,182,268_AL_.jpg");
*/

           Item I4=new Item();
       /* I4.setId(4);
        I4.setName("Friends");
        I4.setGenre("Comedy");
        I4.setImageLink("https://m.media-amazon.com/images/M/MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwZWEtOWVhYjZlYjllYmU4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_UY268_CR0,0,182,268_AL_.jpg");

        */
       /* Item I5=new Item();
        I5.setId(5);
        I5.setName("Money Heist");
        I5.setGenre("Fantasy");
        I5.setImageLink("https://m.media-amazon.com/images/M/MV5BMzBlY2QzNzYtMWU1NS00NjFkLWJiMzItYmM3YTc4MDFjNDQwXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_UX182_CR0,0,182,268_AL_.jpg");
*/
       /* String autogeneratedKey=myRef2.push().getKey();

        myRef2.child(autogeneratedKey).setValue(I5);*/

    }
}
